#!/usr/bin/env node
/**
 * Fetches all CEB areas from the public /Incognito/GetAreasByProvince
 * endpoint for all 9 active provinces, resolves each area name to an
 * approximate centroid via GeoPop's /cities/search, and emits SQL to:
 *
 *   src/db/seed-areas.sql
 *
 * Apply with:
 *   npm run db:seed:local
 *
 * Idempotent: uses INSERT OR REPLACE so re-running is safe.
 *
 * The centroids don't need to be pixel-perfect — they're only used to
 * answer "which CEB areas are near this GPS point?" for the lazy
 * poller (services/ceb.service.ts). ±5 km is fine.
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(__dirname, '../src/db/seed-areas.sql');

const CEB_BASE = 'https://cebcare.ceb.lk';
const GEOPOP_BASE = process.env.GEOPOP_URL || 'http://localhost:8990';

const PROVINCES = [
  { id: 1, code: 'WPN', name: 'Western North' },
  { id: 2, code: 'WPSI', name: 'Western South I' },
  { id: 3, code: 'CC', name: 'Colombo City' },
  { id: 4, code: 'NP', name: 'Northern' },
  { id: 5, code: 'CP', name: 'Central' },
  { id: 6, code: 'UP', name: 'Uva' },
  { id: 7, code: 'EP', name: 'Eastern' },
  { id: 8, code: 'NWP', name: 'North Western' },
  { id: 9, code: 'SBP', name: 'Sabaragamuwa' },
];

const PROVINCE_NAME_BY_CODE = Object.fromEntries(PROVINCES.map((p) => [p.code, p.name]));

function parseDoubleEncoded(raw) {
  if (!raw || raw === '""') return [];
  const first = JSON.parse(raw);
  if (typeof first === 'string') {
    if (!first) return [];
    return JSON.parse(first);
  }
  return first;
}

function sqlEscape(value) {
  if (value === null || value === undefined) return 'NULL';
  return `'${String(value).replace(/'/g, "''")}'`;
}

async function fetchProvince(province) {
  const url = `${CEB_BASE}/Incognito/GetAreasByProvince?provinceId=${province.id}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`CEB ${url} → HTTP ${res.status}`);
  const text = await res.text();
  const areas = parseDoubleEncoded(text);
  return areas.map((a) => ({
    area_id: a.AreaId,
    area_name: a.AreaName,
    province_id: a.ProvinceId,
    province_name: PROVINCE_NAME_BY_CODE[a.ProvinceId] ?? null,
    num_customers: Number(a.NumCustomers ?? 0),
  }));
}

/**
 * Strip decorations like "(North)" or " City" from a CEB area name so
 * GeoPop's fuzzy search can find the underlying place.
 *
 *   "Colombo (North)"  → "Colombo"
 *   "Kandy City"       → "Kandy"
 *   "Jaffna East"      → "Jaffna"
 *   "Western South I"  → "Western South I"  (unchanged, handled below)
 */
function normalizeForSearch(name) {
  return name
    .replace(/\s*\(.*?\)\s*/g, '')
    .replace(/\s+(City|East|West|North|South)$/i, '')
    .trim();
}

async function resolveCentroid(areaName) {
  const query = normalizeForSearch(areaName);
  if (!query) return null;
  const url = `${GEOPOP_BASE}/api/v1/cities/search?q=${encodeURIComponent(query)}&country=LK&limit=3`;
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const body = await res.json();
    const results = body?.payload?.results ?? [];
    if (results.length === 0) return null;
    // Pick the highest-scoring result — already sorted by score desc
    return { lat: results[0].lat, lon: results[0].lon };
  } catch {
    return null;
  }
}

async function main() {
  console.log(`Fetching ${PROVINCES.length} provinces from CEB…`);
  const provinceResults = await Promise.all(PROVINCES.map(fetchProvince));
  const allAreas = provinceResults.flat();
  console.log(`Got ${allAreas.length} areas.`);

  console.log(`\nResolving centroids via GeoPop (${GEOPOP_BASE})…`);
  const resolved = 0;
  let resolvedCount = 0;
  for (const area of allAreas) {
    const centroid = await resolveCentroid(area.area_name);
    if (centroid) {
      area.center_lat = centroid.lat;
      area.center_lon = centroid.lon;
      resolvedCount++;
      process.stdout.write('.');
    } else {
      area.center_lat = null;
      area.center_lon = null;
      process.stdout.write('?');
    }
  }
  console.log(`\nResolved ${resolvedCount} / ${allAreas.length} centroids.`);

  const unresolved = allAreas.filter((a) => a.center_lat == null);
  if (unresolved.length > 0) {
    console.log('\nCould not resolve:');
    unresolved.forEach((a) => console.log(`  ${a.area_id}  ${a.area_name}`));
  }

  const lines = [
    '-- Auto-generated by scripts/seed-areas.js — do not edit by hand.',
    `-- Generated: ${new Date().toISOString()}`,
    `-- Sources: ${CEB_BASE}/Incognito/GetAreasByProvince + GeoPop /cities/search`,
    '',
  ];

  for (const a of allAreas) {
    lines.push(
      `INSERT OR REPLACE INTO areas (area_id, area_name, province_id, province_name, num_customers, center_lat, center_lon, updated_at) VALUES (` +
        [
          sqlEscape(a.area_id),
          sqlEscape(a.area_name),
          sqlEscape(a.province_id),
          sqlEscape(a.province_name),
          a.num_customers,
          a.center_lat ?? 'NULL',
          a.center_lon ?? 'NULL',
          "datetime('now')",
        ].join(', ') +
        ');',
    );
  }

  await mkdir(dirname(OUT_PATH), { recursive: true });
  await writeFile(OUT_PATH, lines.join('\n') + '\n', 'utf8');
  console.log(`\nWrote ${allAreas.length} INSERTs → ${OUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
